- name: Make sure that config partition marker exists
  become: true
  file:
    path: "{{ vyos_install_root }}/opt/vyatta/etc/config/.vyatta_config"
    state: touch

- name: Copy config to the installed image
  become: true
  template:
    src: config.boot.j2
    dest: "{{ vyos_install_root }}/opt/vyatta/etc/config/config.boot"
    mode: 0755
