---
- name: create new iso
  become: true
  command:  > 
    xorriso -as mkisofs -R -r -J -joliet-long -l -cache-inodes \
    -iso-level 3 -isohybrid-mbr /usr/lib/ISOLINUX/isohdpfx.bin \
    -partition_offset 16 -A "VyOS" -p "live-build 1:20190311.1; \
    https://debian-live.alioth.debian.org/live-build" \
    -publisher "autobuild@vyos.net" -V "VyOS" --modification-date={{ lookup('pipe','date +\"%Y%m%d%H%M%S%2N\"') }} \
    -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 \
    -boot-info-table -eltorito-alt-boot  -e boot/grub/efi.img -no-emul-boot \
    -isohybrid-gpt-basdat -isohybrid-apm-hfsplus -o {{ vyos_cloud_upgrade_iso }} /tmp/live-{{ vyos_version }}
