- name: Install required packages
  become: true
  apt:
    update_cache: true
    name:
      - gdisk
      - kpartx
      - dosfstools
      - e2fsprogs
      - gnupg
      - qemu-utils
      - python3-lxml
      - grub-efi-amd64
      - grub-efi-amd64-bin
      - grub-common
      - isolinux
      - python3-requests
      - rsync
      - unzip
      - zlib1g-dev
      - squashfs-tools
      - xorriso
    state: present
