# Unmount all mounts
# If remove unmounted before absent, cannot unmount vyos_install_root...
- name: Unmount {{ vyos_install_root }}/boot
  become: true
  mount:
    name: "{{ vyos_install_root }}/boot"
    src: "{{ vyos_write_root }}"
    fstype: none
    state: unmounted

- name: Unmount {{ vyos_install_root }}/boot
  become: true
  mount:
    name: "{{ vyos_install_root }}/boot"
    src: "{{ vyos_write_root }}"
    fstype: none
    state: absent

- name: Unmount {{ vyos_install_root }}
  become: true
  mount:
    name: "{{ vyos_install_root }}"
    src: overlayfs
    fstype: overlayfs
    state: absent

- name: Unmount {{ vyos_read_root }}
  become: true
  mount:
    name: "{{ vyos_read_root }}"
    src: "{{ vyos_write_root }}/boot/{{ vyos_version }}/{{ vyos_version }}.squashfs"
    fstype: squashfs
    state: absent

- name: Unmount {{ vyos_write_root }}
  become: true
  mount:
    name: "{{ vyos_write_root }}"
    state: absent

- name: Check if the raw image file exists
  stat:
    path: "{{ vyos_raw_img }}"
  register: st

- name: Remove image partitions
  become: true
  command: "kpartx -dv {{ vyos_raw_img }}"
  when: st.stat.exists

- name: Remove /dev/mapper entries
  become: true
  command: "dmsetup remove {{ item }} || true"
  with_items: "{{ loop_partitions.stdout_lines }}"
  when: loop_partitions.stdout_lines is defined
  failed_when: false

- name: Detach {{ loop_device.stdout }}
  become: true
  command: "losetup -d {{ loop_device.stdout }}"
  when: loop_device.stdout is defined
  failed_when: false

- name: Unmount {{ vyos_cd_squash_root }}
  become: true
  mount:
    name: "{{ vyos_cd_squash_root }}"
    src: "{{ vyos_squashfs_image }}"
    fstype: squashfs
    state: absent

- name: Unmount {{ vyos_cd_root }}
  become: true
  mount:
    name: "{{ vyos_cd_root }}"
    src: "{{ vyos_iso_local }}"
    fstype: iso9660
    state: absent
